"""Function blocks of the PLC library (generated by ``tools.st2py``).

Every block can be imported directly from this package (loaded on first use)::

    from srci.fb import MC_EnableRobotFB, MC_MoveAxesAbsoluteFB

The modules follow the folder structure of the PLC library
(e.g. ``srci.fb.BasicMove.MC_MoveAxesAbsolute.MC_MoveAxesAbsoluteFB``).
"""

from __future__ import annotations

import importlib
from typing import Any

from srci.fb._registry import FB_MODULES


def __getattr__(name: str) -> Any:
    module = FB_MODULES.get(name)
    if module is None:
        raise AttributeError(f"module 'srci.fb' has no function block {name!r}")
    value = getattr(importlib.import_module(module), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted([*globals(), *FB_MODULES])
