# -------------------------------------------------------------------------
#  SRCI Robot Library - Python client
# -------------------------------------------------------------------------
#
#  Object:      srci.fb
#  Author:      Thorsten Brach
#  Date:        2026-09-26
#
#  Description:
#    Type stub of the function blocks (generated)
#
#  Copyright:
#    (C) 2026 Thorsten Brach. All rights reserved
#             Licensed under the MIT License.
#
#  Disclaimer:
#    This project is provided without any guarantee and can be used for
#    private and commercial purposes. Any use is at the user's
#    own risk and responsibility.
#
# -------------------------------------------------------------------------

"""Function blocks of the PLC library (generated by tools.st2py)."""

# ruff: noqa
from srci.fb._internal.ActiveCommandRegisterFB import ActiveCommandRegisterFB as ActiveCommandRegisterFB
from srci.fb._internal.LogFBs.AxesGroupMessageLogFB import AxesGroupMessageLogFB as AxesGroupMessageLogFB
from srci.fb._internal.SystemData.AxesGroupSystemDataFB import AxesGroupSystemDataFB as AxesGroupSystemDataFB
from srci.fb.Additional.MC_AbortMeasuringInput.MC_AbortMeasuringInputFB import MC_AbortMeasuringInputFB as MC_AbortMeasuringInputFB
from srci.fb.ConveyorTracking.MC_ActivateConveyorTracking.MC_ActivateConveyorTrackingFB import MC_ActivateConveyorTrackingFB as MC_ActivateConveyorTrackingFB
from srci.fb.Additional.MC_ActivateNextCommand.MC_ActivateNextCommandFB import MC_ActivateNextCommandFB as MC_ActivateNextCommandFB
from srci.fb.WorkAreas.MC_ActivateWorkArea.MC_ActivateWorkAreaFB import MC_ActivateWorkAreaFB as MC_ActivateWorkAreaFB
from srci.fb.Additional.MC_AvoidSingularity.MC_AvoidSingularityFB import MC_AvoidSingularityFB as MC_AvoidSingularityFB
from srci.fb.Additional.MC_BrakeTest.MC_BrakeTestFB import MC_BrakeTestFB as MC_BrakeTestFB
from srci.fb.Calculation.MC_CalculateCartesianPosition.MC_CalculateCartesianPositionFB import MC_CalculateCartesianPositionFB as MC_CalculateCartesianPositionFB
from srci.fb.Calculation.MC_CalculateForwardKinematic.MC_CalculateForwardKinematicFB import MC_CalculateForwardKinematicFB as MC_CalculateForwardKinematicFB
from srci.fb.Calculation.MC_CalculateFrame.MC_CalculateFrameFB import MC_CalculateFrameFB as MC_CalculateFrameFB
from srci.fb.Calculation.MC_CalculateInverseKinematic.MC_CalculateInverseKinematicFB import MC_CalculateInverseKinematicFB as MC_CalculateInverseKinematicFB
from srci.fb.Calculation.MC_CalculateTool.MC_CalculateToolFB import MC_CalculateToolFB as MC_CalculateToolFB
from srci.fb.Additional.MC_CallSubprogram.MC_CallSubprogramFB import MC_CallSubprogramFB as MC_CallSubprogramFB
from srci.fb.BasicMove.MC_ChangeSpeedOverride.MC_ChangeSpeedOverrideFB import MC_ChangeSpeedOverrideFB as MC_ChangeSpeedOverrideFB
from srci.fb.Additional.MC_CollisionDetection.MC_CollisionDetectionFB import MC_CollisionDetectionFB as MC_CollisionDetectionFB
from srci.fb.ConveyorTracking.MC_ConfigureConveyor.MC_ConfigureConveyorFB import MC_ConfigureConveyorFB as MC_ConfigureConveyorFB
from srci.fb.General.MC_CreateServerLog_ToDo.MC_CreateServerLog_ToDo import MC_CreateServerLog_ToDo as MC_CreateServerLog_ToDo
from srci.fb.Spline.MC_CreateSpline.MC_CreateSplineFB import MC_CreateSplineFB as MC_CreateSplineFB
from srci.fb.Spline.MC_DeleteSpline.MC_DeleteSplineFB import MC_DeleteSplineFB as MC_DeleteSplineFB
from srci.fb.Spline.MC_DynamicSpline.MC_DynamicSplineFB import MC_DynamicSplineFB as MC_DynamicSplineFB
from srci.fb.General.MC_EnableRobot.MC_EnableRobotFB import MC_EnableRobotFB as MC_EnableRobotFB
from srci.fb.Additional.MC_ExchangeConfiguration.MC_ExchangeConfigurationFB import MC_ExchangeConfigurationFB as MC_ExchangeConfigurationFB
from srci.fb.ForceControl.MC_ForceControl.MC_ForceControlFB import MC_ForceControlFB as MC_ForceControlFB
from srci.fb.ForceControl.MC_ForceLimit.MC_ForceLimitFB import MC_ForceLimitFB as MC_ForceLimitFB
from srci.fb.Additional.MC_FreeDrive.MC_FreeDriveFB import MC_FreeDriveFB as MC_FreeDriveFB
from srci.fb.BasicMove.MC_GroupContinue.MC_GroupContinueFB import MC_GroupContinueFB as MC_GroupContinueFB
from srci.fb.BasicMove.MC_GroupInterrupt.MC_GroupInterruptFB import MC_GroupInterruptFB as MC_GroupInterruptFB
from srci.fb.BasicMove.MC_GroupJog.MC_GroupJogFB import MC_GroupJogFB as MC_GroupJogFB
from srci.fb.General.MC_GroupReset.MC_GroupResetFB import MC_GroupResetFB as MC_GroupResetFB
from srci.fb.BasicMove.MC_GroupStop.MC_GroupStopFB import MC_GroupStopFB as MC_GroupStopFB
from srci.fb.Calculation.MC_LoadMeasurementAutomatic.MC_LoadMeasurementAutomaticFB import MC_LoadMeasurementAutomaticFB as MC_LoadMeasurementAutomaticFB
from srci.fb.Calculation.MC_LoadMeasurementSequential.MC_LoadMeasurementSequentialFB import MC_LoadMeasurementSequentialFB as MC_LoadMeasurementSequentialFB
from srci.fb.Additional.MC_MeasuringInput.MC_MeasuringInputFB import MC_MeasuringInputFB as MC_MeasuringInputFB
from srci.fb.WorkAreas.MC_MonitorWorkArea.MC_MonitorWorkAreaFB import MC_MonitorWorkAreaFB as MC_MonitorWorkAreaFB
from srci.fb.AdvancedMove.MC_MoveApproachDirect.MC_MoveApproachDirectFB import MC_MoveApproachDirectFB as MC_MoveApproachDirectFB
from srci.fb.AdvancedMove.MC_MoveApproachLinear.MC_MoveApproachLinearFB import MC_MoveApproachLinearFB as MC_MoveApproachLinearFB
from srci.fb.BasicMove.MC_MoveAxesAbsolute.MC_MoveAxesAbsoluteFB import MC_MoveAxesAbsoluteFB as MC_MoveAxesAbsoluteFB
from srci.fb.AdvancedMove.MC_MoveAxesRelative.MC_MoveAxesRelativeFB import MC_MoveAxesRelativeFB as MC_MoveAxesRelativeFB
from srci.fb.AdvancedMove.MC_MoveCircularAbsolute.MC_MoveCircularAbsoluteFB import MC_MoveCircularAbsoluteFB as MC_MoveCircularAbsoluteFB
from srci.fb.AdvancedMove.MC_MoveCircularCamFB.MC_MoveCircularCamFB import MC_MoveCircularCamFB as MC_MoveCircularCamFB
from srci.fb.AdvancedMove.MC_MoveCircularRelative.MC_MoveCircularRelativeFB import MC_MoveCircularRelativeFB as MC_MoveCircularRelativeFB
from srci.fb.AdvancedMove.MC_MoveDepartDirect.MC_MoveDepartDirectFB import MC_MoveDepartDirectFB as MC_MoveDepartDirectFB
from srci.fb.AdvancedMove.MC_MoveDepartLinear.MC_MoveDepartLinearFB import MC_MoveDepartLinearFB as MC_MoveDepartLinearFB
from srci.fb.BasicMove.MC_MoveDirectAbsolute.MC_MoveDirectAbsoluteFB import MC_MoveDirectAbsoluteFB as MC_MoveDirectAbsoluteFB
from srci.fb.AdvancedMove.MC_MoveDirectOffset.MC_MoveDirectOffsetFB import MC_MoveDirectOffsetFB as MC_MoveDirectOffsetFB
from srci.fb.AdvancedMove.MC_MoveDirectRelative.MC_MoveDirectRelativeFB import MC_MoveDirectRelativeFB as MC_MoveDirectRelativeFB
from srci.fb.BasicMove.MC_MoveLinearAbsolute.MC_MoveLinearAbsoluteFB import MC_MoveLinearAbsoluteFB as MC_MoveLinearAbsoluteFB
from srci.fb.AdvancedMove.MC_MoveLinearAbsoluteJ.MC_MoveLinearAbsoluteJFB import MC_MoveLinearAbsoluteJFB as MC_MoveLinearAbsoluteJFB
from srci.fb.AdvancedMove.MC_MoveLinearCam.MC_MoveLinearCamFB import MC_MoveLinearCamFB as MC_MoveLinearCamFB
from srci.fb.AdvancedMove.MC_MoveLinearOffset.MC_MoveLinearOffsetFB import MC_MoveLinearOffsetFB as MC_MoveLinearOffsetFB
from srci.fb.AdvancedMove.MC_MoveLinearRelative.MC_MoveLinearRelativeFB import MC_MoveLinearRelativeFB as MC_MoveLinearRelativeFB
from srci.fb.AdvancedMove.MC_MovePickPlaceDirect.MC_MovePickPlaceDirectFB import MC_MovePickPlaceDirectFB as MC_MovePickPlaceDirectFB
from srci.fb.AdvancedMove.MC_MovePickPlaceLinear.MC_MovePickPlaceLinearFB import MC_MovePickPlaceLinearFB as MC_MovePickPlaceLinearFB
from srci.fb.Spline.MC_MoveSpline.MC_MoveSplineFB import MC_MoveSplineFB as MC_MoveSplineFB
from srci.fb.SuperImposing.MC_MoveSuperImposedDynamic.MC_MoveSuperImposedDynamicFB import MC_MoveSuperImposedDynamicFB as MC_MoveSuperImposedDynamicFB
from srci.fb.SuperImposing.MC_MoveSuperImposed.MC_MoveSuperImposedFB import MC_MoveSuperImposedFB as MC_MoveSuperImposedFB
from srci.fb.Additional.MC_OpenBrake.MC_OpenBrakeFB import MC_OpenBrakeFB as MC_OpenBrakeFB
from srci.fb.Additional.MC_PathAccuracyMode.MC_PathAccuracyModeFB import MC_PathAccuracyModeFB as MC_PathAccuracyModeFB
from srci.fb.Trigger.MC_ReactAtTrigger.MC_ReactAtTriggerFB import MC_ReactAtTriggerFB as MC_ReactAtTriggerFB
from srci.fb.ForceControl.MC_ReadActualForce.MC_ReadActualForceFB import MC_ReadActualForceFB as MC_ReadActualForceFB
from srci.fb.Read.MC_ReadActualPositionCyclic.MC_ReadActualPositionCyclicFB import MC_ReadActualPositionCyclicFB as MC_ReadActualPositionCyclicFB
from srci.fb.Read.MC_ReadActualPosition.MC_ReadActualPositionFB import MC_ReadActualPositionFB as MC_ReadActualPositionFB
from srci.fb.Read.MC_ReadActualTCPVelocity.MC_ReadActualTCPVelocityFB import MC_ReadActualTCPVelocityFB as MC_ReadActualTCPVelocityFB
from srci.fb.Read.MC_ReadAnalogInput.MC_ReadAnalogInputFB import MC_ReadAnalogInputFB as MC_ReadAnalogInputFB
from srci.fb.Additional.MC_ReadCallSubprogramCyclic.MC_ReadCallSubprogramCyclicFB import MC_ReadCallSubprogramCyclicFB as MC_ReadCallSubprogramCyclicFB
from srci.fb.Read.MC_ReadDHParameter.MC_ReadDHParameterFB import MC_ReadDHParameterFB as MC_ReadDHParameterFB
from srci.fb.Read.MC_ReadDigitalInputs.MC_ReadDigitalInputsFB import MC_ReadDigitalInputsFB as MC_ReadDigitalInputsFB
from srci.fb.Read.MC_ReadDigitalOutputs.MC_ReadDigitalOutputsFB import MC_ReadDigitalOutputsFB as MC_ReadDigitalOutputsFB
from srci.fb.Read.MC_ReadFrameData.MC_ReadFrameDataFB import MC_ReadFrameDataFB as MC_ReadFrameDataFB
from srci.fb.Read.MC_ReadIntegers.MC_ReadIntegersFB import MC_ReadIntegersFB as MC_ReadIntegersFB
from srci.fb.Read.MC_ReadLoadData.MC_ReadLoadDataFB import MC_ReadLoadDataFB as MC_ReadLoadDataFB
from srci.fb.Read.MC_ReadMessages.MC_ReadMessagesFB import MC_ReadMessagesFB as MC_ReadMessagesFB
from srci.fb.Read.MC_ReadReals.MC_ReadRealsFB import MC_ReadRealsFB as MC_ReadRealsFB
from srci.fb.Read.MC_ReadRobotData.MC_ReadRobotDataFB import MC_ReadRobotDataFB as MC_ReadRobotDataFB
from srci.fb.Read.MC_ReadRobotDefaultDynamics.MC_ReadRobotDefaultDynamicsFB import MC_ReadRobotDefaultDynamicsFB as MC_ReadRobotDefaultDynamicsFB
from srci.fb.Read.MC_ReadRobotReferenceDynamics.MC_ReadRobotReferenceDynamicsFB import MC_ReadRobotReferenceDynamicsFB as MC_ReadRobotReferenceDynamicsFB
from srci.fb.Read.MC_ReadRobotSWLimits.MC_ReadRobotSWLimitsFB import MC_ReadRobotSWLimitsFB as MC_ReadRobotSWLimitsFB
from srci.fb.General.MC_ReadServerLog_ToDo.MC_ReadServerLog import MC_ReadServerLog as MC_ReadServerLog
from srci.fb.Read.MC_ReadSystemVariable.MC_ReadSystemVariableFB import MC_ReadSystemVariableFB as MC_ReadSystemVariableFB
from srci.fb.Read.MC_ReadToolData.MC_ReadToolDataFB import MC_ReadToolDataFB as MC_ReadToolDataFB
from srci.fb.WorkAreas.MC_ReadWorkArea.MC_ReadWorkAreaFB import MC_ReadWorkAreaFB as MC_ReadWorkAreaFB
from srci.fb.ConveyorTracking.MC_RedefineTrackingPos.MC_RedefineTrackingPosFB import MC_RedefineTrackingPosFB as MC_RedefineTrackingPosFB
from srci.fb.General.MC_RestartController.MC_RestartControllerFB import MC_RestartControllerFB as MC_RestartControllerFB
from srci.fb.BasicMove.MC_ReturnToPrimary.MC_ReturnToPrimaryFB import MC_ReturnToPrimaryFB as MC_ReturnToPrimaryFB
from srci.fb.General.MC_RobotTask.MC_RobotTaskFB import MC_RobotTaskFB as MC_RobotTaskFB
from srci.fb.SearchHardstop.MC_SearchHardStop.MC_SearchHardStopFB import MC_SearchHardStopFB as MC_SearchHardStopFB
from srci.fb.SearchHardstop.MC_SearchHardStopJ.MC_SearchHardStopJFB import MC_SearchHardStopJFB as MC_SearchHardStopJFB
from srci.fb.General.MC_SetOperationMode.MC_SetOperationModeFB import MC_SetOperationModeFB as MC_SetOperationModeFB
from srci.fb.General.MC_SetSequence.MC_SetSequenceFB import MC_SetSequenceFB as MC_SetSequenceFB
from srci.fb.Trigger.MC_SetTriggerError.MC_SetTriggerErrorFB import MC_SetTriggerErrorFB as MC_SetTriggerErrorFB
from srci.fb.Trigger.MC_SetTriggerLimit.MC_SetTriggerLimitFB import MC_SetTriggerLimitFB as MC_SetTriggerLimitFB
from srci.fb.Trigger.MC_SetTriggerMotion.MC_SetTriggerMotionFB import MC_SetTriggerMotionFB as MC_SetTriggerMotionFB
from srci.fb.Trigger.MC_SetTriggerRegister.MC_SetTriggerRegisterFB import MC_SetTriggerRegisterFB as MC_SetTriggerRegisterFB
from srci.fb.Trigger.MC_SetTriggerUser.MC_SetTriggerUserFB import MC_SetTriggerUserFB as MC_SetTriggerUserFB
from srci.fb.Additional.MC_ShiftPosition.MC_ShiftPositionFB import MC_ShiftPositionFB as MC_ShiftPositionFB
from srci.fb.Additional.MC_SoftSwitchTcp.MC_SoftSwitchTcpFB import MC_SoftSwitchTcpFB as MC_SoftSwitchTcpFB
from srci.fb.Additional.MC_StopSubprogram.MC_StopSubprogramFB import MC_StopSubprogramFB as MC_StopSubprogramFB
from srci.fb.General.MC_SwitchLanguage.MC_SwitchLanguageFB import MC_SwitchLanguageFB as MC_SwitchLanguageFB
from srci.fb.ConveyorTracking.MC_SyncToConveyor.MC_SyncToConveyorFB import MC_SyncToConveyorFB as MC_SyncToConveyorFB
from srci.fb.Additional.MC_UnitMeasurement.MC_UnitMeasurementFB import MC_UnitMeasurementFB as MC_UnitMeasurementFB
from srci.fb.General.MC_UserLogin.MC_UserLoginFB import MC_UserLoginFB as MC_UserLoginFB
from srci.fb.Trigger.MC_WaitForTrigger.MC_WaitForTriggerFB import MC_WaitForTriggerFB as MC_WaitForTriggerFB
from srci.fb.Trigger.MC_WaitTime.MC_WaitTimeFB import MC_WaitTimeFB as MC_WaitTimeFB
from srci.fb.Write.MC_WriteAnalogOutput.MC_WriteAnalogOutputFB import MC_WriteAnalogOutputFB as MC_WriteAnalogOutputFB
from srci.fb.Additional.MC_WriteCallSubprogramCyclic.MC_WriteCallSubprogramCyclicFB import MC_WriteCallSubprogramCyclicFB as MC_WriteCallSubprogramCyclicFB
from srci.fb.Write.MC_WriteDigitalOutputs.MC_WriteDigitalOutputsFB import MC_WriteDigitalOutputsFB as MC_WriteDigitalOutputsFB
from srci.fb.Write.MC_WriteFrameData.MC_WriteFrameDataFB import MC_WriteFrameDataFB as MC_WriteFrameDataFB
from srci.fb.Write.MC_WriteIntegers.MC_WriteIntegersFB import MC_WriteIntegersFB as MC_WriteIntegersFB
from srci.fb.Write.MC_WriteLoadData.MC_WriteLoadDataFB import MC_WriteLoadDataFB as MC_WriteLoadDataFB
from srci.fb.Write.MC_WriteReals.MC_WriteRealsFB import MC_WriteRealsFB as MC_WriteRealsFB
from srci.fb.Write.MC_WriteRobotDefaultDynamics.MC_WriteRobotDefaultDynamicsFB import MC_WriteRobotDefaultDynamicsFB as MC_WriteRobotDefaultDynamicsFB
from srci.fb.Write.MC_WriteRobotReferenceDynamics.MC_WriteRobotReferenceDynamicsFB import MC_WriteRobotReferenceDynamicsFB as MC_WriteRobotReferenceDynamicsFB
from srci.fb.Write.MC_WriteRobotSWLimits.MC_WriteRobotSWLimitsFB import MC_WriteRobotSWLimitsFB as MC_WriteRobotSWLimitsFB
from srci.fb.Write.MC_WriteSystemVariable.MC_WriteSystemVariableFB import MC_WriteSystemVariableFB as MC_WriteSystemVariableFB
from srci.fb.Write.MC_WriteToolData.MC_WriteToolDataFB import MC_WriteToolDataFB as MC_WriteToolDataFB
from srci.fb.WorkAreas.MC_WriteWorkArea.MC_WriteWorkAreaFB import MC_WriteWorkAreaFB as MC_WriteWorkAreaFB
from srci.fb._internal.BaseFBs.RobotLibraryBaseEnableFB import RobotLibraryBaseEnableFB as RobotLibraryBaseEnableFB
from srci.fb._internal.BaseFBs.RobotLibraryBaseExecuteFB import RobotLibraryBaseExecuteFB as RobotLibraryBaseExecuteFB
from srci.fb._internal.BaseFBs.RobotLibraryBaseFB import RobotLibraryBaseFB as RobotLibraryBaseFB
from srci.fb._internal.Send.RobotLibraryCommandDataFB import RobotLibraryCommandDataFB as RobotLibraryCommandDataFB
from srci.fb._internal.BaseFBs.RobotLibraryLogFB import RobotLibraryLogFB as RobotLibraryLogFB
from srci.fb._internal.Recv.RobotLibraryRecvDataBaseFB import RobotLibraryRecvDataBaseFB as RobotLibraryRecvDataBaseFB
from srci.fb._internal.Recv.RobotLibraryRecvDataFB import RobotLibraryRecvDataFB as RobotLibraryRecvDataFB
from srci.fb._internal.Recv.RobotLibraryResponseDataFB import RobotLibraryResponseDataFB as RobotLibraryResponseDataFB
from srci.fb._internal.Send.RobotLibrarySendDataBaseFB import RobotLibrarySendDataBaseFB as RobotLibrarySendDataBaseFB
from srci.fb._internal.Send.RobotLibrarySendDataFB import RobotLibrarySendDataFB as RobotLibrarySendDataFB
