"""docs/TestCases.md: catalog of all test cases (registry + number of instances + coverage of
the Siemens test case templates)."""

from __future__ import annotations

import json
import subprocess
import sys
from collections import Counter
from pathlib import Path
from typing import Any

from tools.test_report import registry

ROOT = registry.ROOT
TARGET = ROOT / "docs" / "TestCases.md"
SIEMENS = ROOT / "docs" / "siemens_mapping.json"

CATEGORIES = {
    "A": "automated - the test case (or its client part) is a test of SRCI_PY",
    "P": "partly - the client part is automated, the reaction of the robot controller is only simulated",
    "R": "RC behavior - the result is decided by the robot controller (motion, blending, dynamics, "
    "trigger ...); the client part is the correct transfer of the parameters (SDK-BIL) and of the RC "
    "errors (ERR-02)",
    "N": "not applicable - precondition rows, display in the PLC IDE, release checks of the PLC library",
}


def collect_counts() -> Counter[str]:
    """Number of collected instances per test function (``pytest --collect-only``)."""
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "--collect-only", "-q", "-p", "no:cacheprovider"],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    counts: Counter[str] = Counter()
    for line in result.stdout.splitlines():
        if line.startswith("tests/") and "::" in line:
            counts[line.split("[", 1)[0]] += 1
    return counts


def _md(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def _full_description(test: str) -> str:
    for function in registry.scan():
        if function.test == test:
            text, _ = registry.split_doc(function.docstring)
            return text[:1].upper() + text[1:]
    return ""


def render(entries: list[dict[str, Any]], counts: Counter[str]) -> str:
    active = [e for e in entries if e.get("status") == "active"]
    names = registry.area_names()
    per_area: dict[str, list[dict[str, Any]]] = {}
    for entry in active:
        code, _ = registry.area_of(str(entry["test"]))
        per_area.setdefault(code, []).append(entry)
    out = [
        "# SRCI_PY - Test cases",
        "",
        "<!-- GENERATED by `python -m tools.test_report catalog` from tests/testcases.json. DO NOT EDIT. -->",
        "",
        "Every test function has a unique, stable test case ID (registry `tests/testcases.json`,",
        "`python -m tools.test_report update` assigns IDs to new tests; IDs of removed tests are retired",
        "and never reused). A parametrized test case runs once per function block or parameter set;",
        "these instances are reported as `<ID>[<parameter>]`, e.g. `GEN-05[MC_MoveLinearAbsoluteFB]`.",
        "",
        "Test report (Markdown + HTML, quality evidence of a release):",
        "",
        "```",
        "pytest --tc-report build/test-report",
        "```",
        "",
        'Tests of the areas `MET`, `SDK-*` run against the SRCI SDK simulator ("SDK in the loop",',
        "built locally from the private SDK); without it they are skipped. Known deviations of the PLC",
        "library are `xfail` with the finding of [ST_FINDINGS.md](ST_FINDINGS.md).",
        "",
        "## Overview",
        "",
        "| Area | Description | Test cases | Instances |",
        "|---|---|---:|---:|",
    ]
    total_cases = total_instances = 0
    for code, items in per_area.items():
        instances = sum(counts.get(str(e["test"]), 0) for e in items)
        total_cases += len(items)
        total_instances += instances
        out.append(f"| [{code}](#{code.lower()}) | {names[code]} | {len(items)} | {instances} |")
    out += [f"| | **Total** | **{total_cases}** | **{total_instances}** |", ""]

    order = ["GEN", "ERR", "PM", "SEQ", "REP", "BUF"]
    methodology = sorted(
        (e for e in active if registry.PATTERN_ID.match(str(e["id"]))),
        key=lambda e: (order.index(str(e["id"]).split("-")[0]), str(e["id"])),
    )
    out += [
        "## Test methodology",
        "",
        'The test series of the Siemens unit test templates ("General FB", "ErrorID",',
        '"ProcessingMode", "SequenceFlag", ...) are applied as patterns to **all** function blocks of',
        "the library, also to the ones without a Siemens template:",
        "",
        "| ID | Test | Instances | Reference |",
        "|---|---|---:|---|",
    ]
    for entry in methodology:
        refs = "; ".join(str(r) for r in entry.get("refs", []))
        out.append(
            f"| {entry['id']} | {_md(_full_description(str(entry['test'])))} | "
            f"{counts.get(str(entry['test']), 0)} | {_md(refs)} |"
        )
    out.append("")
    out += _siemens_section()
    for code, items in per_area.items():
        out += [
            f"## {code}",
            "",
            names[code],
            "",
            "| ID | Test case | Instances | Test |",
            "|---|---|---:|---|",
        ]
        for entry in items:
            test = str(entry["test"])
            out.append(
                f"| {entry['id']} | {_md(entry['title'])} | {counts.get(test, 0)} | `{test.split('::', 1)[1]}` |"
            )
        out.append("")
    return "\n".join(out)


def _siemens_section() -> list[str]:
    if not SIEMENS.exists():
        return []
    data = json.loads(SIEMENS.read_text(encoding="utf-8"))
    cases = [dict(zip(data["columns"], row, strict=True)) for row in data["cases"]]
    by_category = Counter(c["category"] for c in cases)
    out = [
        "## Coverage of the Siemens test case templates",
        "",
        f"{data['source']}: {len(cases)} test cases. Every test case is classified (rules, IDs and",
        "SRCI_PY tests per test case in [siemens_mapping.json](siemens_mapping.json)):",
        "",
        "| Category | Test cases | Meaning |",
        "|---|---:|---|",
    ]
    out += [f"| {k} | {by_category[k]} | {v} |" for k, v in CATEGORIES.items()]
    out += ["", "| Test series | A | P | R | N | SRCI_PY tests |", "|---|---:|---:|---:|---:|---|"]
    series: dict[str, Counter[str]] = {}
    tests: dict[str, Counter[str]] = {}
    for case in cases:
        series.setdefault(case["series"], Counter())[case["category"]] += 1
        for test in filter(None, (t.strip() for t in case["tests"].split(","))):
            tests.setdefault(case["series"], Counter())[test] += 1
    for name, counter in sorted(series.items(), key=lambda kv: -sum(kv[1].values())):
        used = ", ".join(t for t, _ in tests.get(name, Counter()).most_common())
        out.append(
            f"| {_md(name)} | {counter['A']} | {counter['P']} | {counter['R']} | {counter['N']} | {_md(used)} |"
        )
    out.append("")
    return out


def write(path: Path = TARGET) -> None:
    path.write_text(render(registry.load(), collect_counts()), encoding="utf-8", newline="\n")
